# Generated by Django 3.1.2 on 2020-10-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='created',
            new_name='data_creation',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated',
        ),
        migrations.AddField(
            model_name='service',
            name='data_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='../static/store/service_item.png', upload_to='store'),
        ),
    ]
