# Generated by Django 3.1.2 on 2020-10-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20201012_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='../static/store/service_item.png', null=True, upload_to='store'),
        ),
    ]
