# Generated by Django 3.1.2 on 2020-10-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20201012_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Sevicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
